__title__ = 'wraplite'
__description__ = 'Python No SQL SQLite Wrapper'
__version__ = '0.2.3-dev27'
__author__ = 'Rui Pires'
__author_email__ = 'ruipiresc@gmail.com'
__license__ = 'GPLv3'
__url__ = 'https://github.com/ruipiresc/ruipiresc.python.wraplite'